spring:
  # Auto-configuration exclusions
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.neo4j.Neo4jAutoConfiguration

  # Database Configuration
  datasource:
    primary:
      url: jdbc:postgresql://localhost:8098/docloader
      username: app_user
      password: app_user_password
      driver-class-name: org.postgresql.Driver
  
  # JPA Configuration  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  # Liquibase Configuration  
  liquibase:
    enabled: true
    user: liquibase_user
    password: liquibase_password
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:8098/docloader
    default-schema: app
    liquibase-schema: app
    
  # Redis Configuration for Session Management  
  data:
    redis:
      host: localhost
      port: 6379
      password: redis_password
      
    # Neo4j Configuration
    neo4j:
      uri: bolt://localhost:7687
      authentication:
        username: neo4j
        password: neo4j_password
  
  # Spring AI Configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:replace_with_real_key}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      
  # Session Configuration  
  session:
    store-type: redis
    redis:
      namespace: docloader:session
    timeout: 3600
  
  # Quartz Configuration for Job Scheduling
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # We're handling schema creation through Liquibase
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.useProperties: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 5
      # Configure Quartz to use app schema and proper table prefix
      org.quartz.jobStore.tablePrefix: app.qrtz_
      org.quartz.jobStore.dataSource: myDS
      org.quartz.dataSource.myDS.provider: hikaricp
      org.quartz.dataSource.myDS.URL: jdbc:postgresql://localhost:8098/docloader
      org.quartz.dataSource.myDS.user: app_user
      org.quartz.dataSource.myDS.password: app_user_password
      org.quartz.dataSource.myDS.driver: org.postgresql.Driver

# Management and Health Checks
management:
  health:
    neo4j:
      enabled: false  # Disable Neo4j health check if it keeps causing issues
      
# Weaviate Vector Database Configuration
weaviate:
  url: http://localhost:8097
  
# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /api
  # CORS Configuration
  cors:
    allowed-origins: http://localhost:3000, http://localhost:3001
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allowed-headers: Authorization, Content-Type
    allow-credentials: true
    max-age: 3600
    
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourJwtSecretKeyHereMakeItAtLeast32CharsLong}
  expiration: 604800000  # 7 days in milliseconds (was 86400000 - 24 hours)
  
# Application Specific Configuration
docloader:
  multi-tenancy:
    enabled: true
    tenant-resolver-strategy: SUBDOMAIN  # Options: SUBDOMAIN, HEADER, PATH
  s3:
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY:minio_access_key}
    secret-key: ${AWS_SECRET_KEY:minio_secret_key}
    bucket-name: ${S3_BUCKET_NAME:docloader}
    path-style-access: ${S3_PATH_STYLE:true}  # Required for MinIO compatibility 
  weaviate:
    enabled: true
  neo4j:
    enabled: false  # Disable Neo4j functionality for now

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationIdStrategy: METHOD
    tryItOutEnabled: true
    filter: true
    tagsSorter: alpha
    display-request-duration: true 