spring:
  # Database Configuration
  datasource:
    primary:
      url: jdbc:postgresql://postgres:5432/docloader
      username: app_user
      password: app_user_password
      driver-class-name: org.postgresql.Driver
  
  # JPA Configuration  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  # Liquibase Configuration  
  liquibase:
    enabled: true
    user: liquibase_user
    password: liquibase_password
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://postgres:5432/docloader
    
  # Redis Configuration for Session Management  
  data:
    redis:
      host: redis
      port: 6379
      password: redis_password
  
  # Spring AI Configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      
  # Session Configuration  
  session:
    store-type: redis
    redis:
      namespace: docloader:session
    timeout: 3600
  
  # Quartz Configuration for Job Scheduling
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.useProperties: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 5

# Neo4j Configuration
neo4j:
  uri: bolt://neo4j:7687
  authentication:
    username: neo4j
    password: neo4j_password

# Weaviate Vector Database Configuration
weaviate:
  url: http://weaviate:8080
  
# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /api
    
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourJwtSecretKeyHereMakeItAtLeast32CharsLong}
  expiration: 86400000  # 24 hours in milliseconds
  
# Application Specific Configuration
docloader:
  multi-tenancy:
    enabled: true
    tenant-resolver-strategy: SUBDOMAIN  # Options: SUBDOMAIN, HEADER, PATH
  s3:
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:} 